server:
  port: 8888

spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BlenoClaus/doe-backend-configs
          search-paths: user
