spring:
  application:
    name: items
  data:
    elasticsearch:
      properties:
        node:
          master: true
        http:
          enabled: true
      repositories:
        enabled: true
      cluster-nodes: localhost:9300
      cluster-name: es-docker-cluster

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081